#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import os

# Ajouter le chemin du projet au PYTHONPATH
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, project_root)

from src.package_manager.cli import main
main()